refactor: Commonified HTML layout for ItemGroupGrid and BrandGrid
ParaLogicTech/portal pull request #6
Opened 2024-04-24 13:28 UTC by Wasiq-Ali

2024-04-26 09:17 UTC, SaiFi0102 requested changes
Commonify ItemGrid.vue as well

2024-04-26 09:17 UTC, SaiFi0102 commented on frontend/src/components/ItemGroup/ItemGroupGrid.vue
> +	name: "BrandGrid",
Revert

2024-04-26 09:20 UTC, Wasiq-Ali commented on frontend/src/components/ItemGroup/ItemGroupGrid.vue
> +	name: "BrandGrid",
Done

2024-04-29 11:34 UTC, SaiFi0102 approved these changes

2024-04-29 11:35 UTC, merged